#!/usr/bin/env python
"""Local LTX-2.5 video worker for the MasSurge pipeline.

Loads the LTX-2.5 distilled two-stage pipeline (video + synchronized speech audio) once and
serves it on localhost, so every shot of a creative is generated by the same resident model:

    cd /scratch1/home/zhicao/models/LTX-2 && CUDA_VISIBLE_DEVICES=5 \\
      uv run python /scratch1/home/zhicao/vidai/agent/scripts/ltx_worker.py \\
      --models /scratch1/home/zhicao/models/ltx-2.5 --port 8765 --quantization fp8-cast --offload none

    GET  /health            -> {"ok": true, "model": "...", "busy": false}
    POST /generate          -> {"prompt", "image" (optional first-frame path), "width", "height",
                                "num_frames", "fps", "seed", "output_path", "first_frame_strength"}
                            <- {"output_path": "...", "seconds": 12.3, "num_frames": 121}

Run it with the LTX-2 repo's uv environment (python >= 3.12, torch, ltx_pipelines).
"""

from __future__ import annotations

import argparse
import json
import logging
import threading
import time
import traceback
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

logger = logging.getLogger("ltx_worker")

FILES = {
    "transformer": "diffusion_models/ltx-2.5-22b-distilled-transformer-bf16.safetensors",
    "text_encoder": "text_encoders/gemma4-12b-with-proj-ltx-2.5-bf16.safetensors",
    "video_vae": "vae/ltx-2.5-video-vae-bf16.safetensors",
    "video_vae_conv": "vae/ltx-2.5-video-vae-conv-bf16.safetensors",
    "audio_vae": "vae/ltx-2.5-audio-vae-bf16.safetensors",
    "duration_head": "model_patches/ltx-2.5-duration-head-bf16.safetensors",
    "spatial_upsampler": "latent_upscale_models/ltx-2.5-latent-spatial-upscaler-x2-bf16-1.0.safetensors",
}


def build_pipeline(models: Path, quantization: str, offload: str, conv_vae: bool):
    import torch  # noqa: F401  (import here so --help works without torch)
    from ltx_core.quantization.fp8_cast import build_policy as build_fp8_cast_policy
    from ltx_pipelines.distilled import DistilledPipeline
    from ltx_pipelines.utils.model_paths import ModelPaths
    from ltx_pipelines.utils.types import OffloadMode

    def path(key: str) -> str:
        candidate = models / FILES[key]
        if not candidate.is_file():
            raise SystemExit(f"missing weight file: {candidate}")
        return str(candidate)

    policy = None
    if quantization == "fp8-cast":
        policy = build_fp8_cast_policy(path("transformer"))   # FP8 weights, bf16 upcast at matmul time
    elif quantization not in ("none", ""):
        raise SystemExit(f"unsupported --quantization {quantization}")
    model_paths = ModelPaths.from_split(
        transformer_path=path("transformer"),
        text_encoder_path=path("text_encoder"),
        video_vae_path=path("video_vae_conv" if conv_vae else "video_vae"),
        audio_vae_path=path("audio_vae"),
        duration_head_path=str(models / FILES["duration_head"]) if (models / FILES["duration_head"]).is_file() else None,
    )
    logger.info("loading LTX-2.5 distilled pipeline from %s (quantization=%s, offload=%s)", models, quantization, offload)
    started = time.time()
    pipeline = DistilledPipeline(
        model_paths=model_paths,
        spatial_upsampler_path=path("spatial_upsampler"),
        loras=(),
        quantization=policy,
        offload_mode=OffloadMode(offload),
    )
    logger.info("pipeline ready in %.0fs", time.time() - started)
    return pipeline


class Worker:
    def __init__(self, pipeline, model_name: str):
        self.pipeline = pipeline
        self.model_name = model_name
        self.lock = threading.Lock()
        self.busy = False
        self.generated = 0

    def generate(self, req: dict[str, Any]) -> dict[str, Any]:
        from ltx_core.model.video_vae import get_video_chunks_number
        from ltx_pipelines.utils.media_io import encode_video
        from ltx_pipelines.utils.types import ImageConditioningInput

        prompt = str(req["prompt"])
        width, height = int(req["width"]), int(req["height"])
        num_frames = int(req.get("num_frames") or 121)
        fps = int(req.get("fps") or 24)
        seed = int(req.get("seed") or 42)
        output_path = Path(req["output_path"])
        output_path.parent.mkdir(parents=True, exist_ok=True)
        images = []
        if req.get("image"):
            image = Path(req["image"])
            if not image.is_file():
                raise FileNotFoundError(f"first frame image not found: {image}")
            images.append(ImageConditioningInput(str(image), 0, float(req.get("first_frame_strength") or 1.0)))
        started = time.time()
        with self.lock:
            self.busy = True
            try:
                result = self.pipeline(
                    prompt=prompt, seed=seed, height=height, width=width, frame_rate=fps,
                    images=images, num_frames=num_frames,
                )
                encode_video(
                    video=result.video, fps=fps, audio=result.audio, output_path=str(output_path),
                    video_chunks_number=get_video_chunks_number(result.num_frames, result.tiling_config),
                )
            finally:
                self.busy = False
        self.generated += 1
        seconds = time.time() - started
        logger.info("generated %s (%dx%d, %d frames, seed %d) in %.1fs", output_path, width, height, num_frames, seed, seconds)
        return {"output_path": str(output_path), "seconds": round(seconds, 1), "num_frames": num_frames,
                "width": width, "height": height, "model": self.model_name}


def make_handler(worker: Worker):
    class Handler(BaseHTTPRequestHandler):
        def _send(self, code: int, payload: dict[str, Any]) -> None:
            body = json.dumps(payload).encode("utf-8")
            self.send_response(code)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def do_GET(self) -> None:  # noqa: N802
            if self.path.startswith("/health"):
                self._send(200, {"ok": True, "model": worker.model_name, "busy": worker.busy, "generated": worker.generated})
            else:
                self._send(404, {"error": "unknown path"})

        def do_POST(self) -> None:  # noqa: N802
            if not self.path.startswith("/generate"):
                self._send(404, {"error": "unknown path"})
                return
            try:
                length = int(self.headers.get("Content-Length") or 0)
                req = json.loads(self.rfile.read(length) or b"{}")
                self._send(200, worker.generate(req))
            except (KeyError, ValueError, FileNotFoundError, AssertionError) as exc:
                self._send(400, {"error": f"{type(exc).__name__}: {exc}"})
            except Exception as exc:  # model / CUDA failure: report, keep serving
                logger.error("generation failed: %s\n%s", exc, traceback.format_exc())
                self._send(500, {"error": f"{type(exc).__name__}: {str(exc)[:500]}"})

        def log_message(self, fmt: str, *args: Any) -> None:
            logger.debug(fmt, *args)

    return Handler


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--models", required=True, help="Directory holding the LTX-2.5 weight files (hf download --local-dir)")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    parser.add_argument("--quantization", default="fp8-cast", choices=["fp8-cast", "none"])
    parser.add_argument("--offload", default="none", choices=["none", "cpu", "disk"])
    parser.add_argument("--conv-vae", action="store_true", help="Use the lighter convolutional video VAE")
    parser.add_argument("--model-name", default="ltx-2.5-22b-distilled")
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    worker = Worker(build_pipeline(Path(args.models), args.quantization, args.offload, args.conv_vae), args.model_name)
    server = ThreadingHTTPServer((args.host, args.port), make_handler(worker))
    logger.info("serving on http://%s:%d  (POST /generate, GET /health)", args.host, args.port)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
